env:
  browser: true
  es6: true
  node: true
extends:
  - "plugin:react/recommended"
  - react-app
  - airbnb-typescript
  - airbnb-typescript-prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/lines-between-class-members": off,
    "@typescript-eslint/dot-notation": off,
    "@typescript-eslint/no-unused-vars":
      ["error", { "argsIgnorePattern": "^_" }],
    "import/prefer-default-export": off,
    "react/jsx-props-no-spreading": off,
    "no-console": 0,
  }
