env:
  es2020: true
  node: true
extends:
  - "plugin:react/recommended"
  - airbnb-typescript
  - airbnb-typescript-prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-unused-vars":
      ["error", { "argsIgnorePattern": "^_" }],
  }
